# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18.0-alpha.19

# Mod Properties
mod_version=0.14.311
maven_group=me.drex.polymerpatcher
archives_base_name=polymer-patcher-plus-plus


# Dependencies
fabric_version=0.158.0+26.2

polymer_version=0.17.5+26.2
factorytools_version=0.11.2+26.2
resource_locator_version=0.8.0+26.2
sgui_version=2.1.0+26.2
enderscape_version=4DwOA1hE
mixinsquared_version=0.3.3
